baseurl = "/"
languageCode = "en"
title = "Mary Mcdonnell"

[params]
  description = "Artist in Slane" 

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
# [[menu.main]]
#     name = "About test"
#     url  = "/about-test"
#     weight = 5

[[menu.main]]
    name = "Exhibition"
    url  = "/exhibition"
    weight = 3
[[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 2
[[menu.main]]
name = "Teaching"
url = "/teaching"
weight = 4
# need to spend time working how dev content section should work
# [[menu.main]]
# name = "Dev"
# url = "/dev"
# weight = 5
# testing purposes only
# [[menu.main]]
# name = "Food"
# url = "/food"
# weight = 6
