baseurl = "/"
languageCode = "en"
title = "Mary Mcdonnell"

[params]
  description = "Artist in Slane" 

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Exhibition"
    url  = "/exhibition"
    weight = 3
# [[menu.main]]
#     name = "Gallery"
#     url = "/gallery"
#     weight = 2
